import {
  FaArrowLeft,
  FaArrowRight,
  FaBox,
  FaBuffer,
  FaBuilding,
  FaChartPie,
  FaCog,
  FaHeadset,
  FaImage,
  FaPlug,
  FaRegWindowMaximize,
  FaTools,
  FaUsers,
} from 'react-icons/fa';
import {
  FaBagShopping,
  FaCartShopping,
  FaEarthAmericas,
  FaHouseChimney,
  FaRegFolderClosed,
  FaScaleBalanced,
  FaShieldHalved,
  FaSquarePollHorizontal,
} from 'react-icons/fa6';

const NavIcons = {
  accounting: <FaScaleBalanced />,
  assets: <FaBagShopping />,
  tool: <FaTools />,
  buying: <FaCartShopping />,
  crm: <FaChartPie />,
  integration: <FaPlug />,
  setting: <FaCog />,
  file: <FaRegFolderClosed />,
  gettingstarted: <FaHouseChimney />,
  organization: <FaBuilding />,
  arrowleft: <FaArrowLeft />,
  project: <FaBuffer />,
  quality: <FaShieldHalved />,
  arrowright: <FaArrowRight />,
  text: <FaRegWindowMaximize />,
  sell: <FaSquarePollHorizontal />,
  stock: <FaBox />,
  support: <FaHeadset />,
  users: <FaUsers />,
  website: <FaEarthAmericas />,
  imageview: <FaImage />,
};
export default NavIcons;
