CREATE TABLE [dbo].[T_PLACE](
	[id_place_key] [int] IDENTITY(100000,1) NOT NULL,
	[id_place_ver] [int] NOT NULL,
	[is_active] [bit] NOT NULL,
	[id_ds_env] [int] NOT NULL,
	[dtt_mod] [datetime] NULL,
	[id_user_mod] [int] NULL,
	[id_env_key] [int] NULL,
	[id_event_key] [int] NULL,
	[id_state_key] [int] NULL,
	[id_action_key] [int] NULL,
	[dtt_added] [datetime] NULL,
	[tx_block_no] [varchar](16) NULL,
	[tx_amenity_feature] [varchar](64) NULL,
	[tx_telephone] [varchar](32) NULL,
	[tx_alternate_name] [varchar](128) NULL,
	[tx_description] [varchar](1024) NULL,
	[tx_identifier] [varchar](128) NULL,
	[tx_global_location_number] [varchar](16) NULL,
	[tx_counter] [varchar](16) NULL,
	[tx_counter_code] [varchar](16) NULL,
	[dtt_opening_hours_spec] [datetime2](6) NULL,
	[flt_latitude] [numeric](14, 6) NULL,
	[flt_longitude] [numeric](15, 6) NULL,
	[flt_floor_size] [numeric](13, 3) NULL,
	[ct_floor_level] [int] NULL,
	[ct_number_of_rooms] [int] NULL,
	[ct_number_of_bedrooms] [int] NULL,
	[ct_maximum_attendee_capacity] [int] NULL,
	[ct_number_of_bathrooms_total] [int] NULL,
	[ct_number_of_full_bathrooms] [int] NULL,
	[ct_number_of_Partial_bathrooms] [int] NULL,
	[is_permitted_usage] [bit] NULL,
	[is_pets_allowed] [bit] NULL,
	[is_accessible_for_free] [bit] NULL,
	[is_drive_through_service] [bit] NULL,
	[is_public_access] [bit] NULL,
	[tx_holding_no] [varchar](16) NULL,
	[tx_room_no] [varchar](16) NULL,
	[tx_table_no] [varchar](16) NULL,
	[tx_comment] [varchar](150) NULL,
	[id_user_gen] [int] NULL,
 CONSTRAINT [PK_T_PLACE] PRIMARY KEY CLUSTERED 
(
	[id_place_key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO