CREATE TABLE Product (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    brand VARCHAR(255),
    category VARCHAR(255),    
    slogan VARCHAR(255),
    description TEXT
);

CREATE TABLE ProductDetails (
    productID INT UNSIGNED NOT NULL,
    additionalProperty TEXT,
    aggregateRating JSON,
    audience VARCHAR(255),
    award VARCHAR(255),
    countryOfAssembly VARCHAR(255),
    countryOfLastProcessing VARCHAR(255),
    countryOfOrigin VARCHAR(255),
    funding VARCHAR(255),
    hasAdultConsideration BOOLEAN,
    hasEnergyConsumptionDetails BOOLEAN,
    hasMeasurement BOOLEAN,
    hasMerchantReturnPolicy BOOLEAN,
    inProductGroupWithID INT UNSIGNED,
    keywords VARCHAR(255),
    logo VARCHAR(255),
    manufacturer VARCHAR(255),
    model VARCHAR(255),
    mpn VARCHAR(255),
    negativeNotes VARCHAR(255),
    offers JSON,
    pattern VARCHAR(255),
    positiveNotes VARCHAR(255),
    productionDate DATE,
    purchaseDate DATE,
    releaseDate DATE,
    review JSON,
    FOREIGN KEY (productID) REFERENCES Product(id)
);
CREATE TABLE ProductPrice (
    productID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    retailPrice DECIMAL(10,2),
    salePrice DECIMAL(10,2),
    discount DECIMAL(5,2),
    currency VARCHAR(10),
    availability VARCHAR(20),
    isAvailable BOOLEAN,
    isOnSale BOOLEAN,
    isFeatured BOOLEAN,
    isLimitedStock BOOLEAN,
    stockQuantity INT,
    soldQuantity INT,
    rating DECIMAL(3,2),
    reviewCount INT,
    createdAt TIMESTAMP,
    updatedAt TIMESTAMP,
    FOREIGN KEY (productID) REFERENCES Product(id)
)
CREATE TABLE ProductIdentifiers (
    productID INT UNSIGNED NOT NULL,
    asin VARCHAR(10),
    gtin VARCHAR(14),
    gtin12 VARCHAR(12),
    gtin13 VARCHAR(13),
    gtin14 VARCHAR(14),
    gtin8 VARCHAR(8),
    nsn VARCHAR(255),
    sku VARCHAR(32),
    upc VARCHAR(32),
    color VARCHAR(255),
    depth DECIMAL(10,2),
    height DECIMAL(10,2),
    weight DECIMAL(10,2),
    width DECIMAL(10,2),
    material VARCHAR(255),
    unitType VARCHAR(255),
    quentatyOfEachUnit VARCHAR(255),    
    size VARCHAR(255),
    FOREIGN KEY (productID) REFERENCES Product(id)
);

CREATE TABLE ProductRelations (
    productID INT UNSIGNED NOT NULL,
    isAccessoryOrSparePartFor INT UNSIGNED,
    isConsumableFor INT UNSIGNED,
    isFamilyFriendly BOOLEAN,
    isRelatedTo INT UNSIGNED,
    isSimilarTo INT UNSIGNED,
    isRecommendedFor INT UNSIGNED,
    isFeaturedIn INT UNSIGNED,
    isPopularIn INT UNSIGNED,
    isTrendingIn INT UNSIGNED,
    isFeaturedInCategory VARCHAR(255),
    isPopularInRegion VARCHAR(255),
    isRecommendedForUser INT UNSIGNED,
    isSimilarToProduct INT UNSIGNED,
    isRelatedToProduct INT UNSIGNED,
    isAccessoryForProduct INT UNSIGNED,
    isSparePartForProduct INT UNSIGNED,
    isConsumableForProduct INT UNSIGNED,
    isVariantOf INT UNSIGNED,    
    FOREIGN KEY (productID) REFERENCES Product(id)
    FOREIGN KEY (productID) REFERENCES Product(id)
);

CREATE TABLE ProductMeta (
    productID INT UNSIGNED NOT NULL,
    additionalType VARCHAR(255),
    alternateName VARCHAR(255),
    disambiguatingDescription VARCHAR(255),
    identifier VARCHAR(255),
    image VARCHAR(255),
    mainEntityOfPage VARCHAR(255),
    mobileUrl VARCHAR(255),
    potentialAction JSON,
    sameAs VARCHAR(255),
    subjectOf VARCHAR(255),
    about VARCHAR(255),
    creator VARCHAR(255),
    contributor VARCHAR(255),
    publisher VARCHAR(255),
    datePublished DATE,
    dateModified DATE,
    version VARCHAR(255),
    url VARCHAR(255),
    FOREIGN KEY (productID) REFERENCES Product(id)
);

CREATE TABLE ProductReviews (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    productID INT UNSIGNED NOT NULL,
    userID INT UNSIGNED NOT NULL,
    rating DECIMAL(3,2),
    review TEXT,
    reviewDate DATE,
    reviewTitle VARCHAR(255),
    reviewAuthor VARCHAR(255),
    reviewAuthorRating DECIMAL(3,2),
    reviewAuthorLocation VARCHAR(255),
    reviewAuthorWebsite VARCHAR(255),    
    recommends BOOLEAN,
    helpfulCount INT DEFAULT 0,
    notHelpfulCount INT DEFAULT 0,
    reviewSource VARCHAR(255),
    verifiedPurchase BOOLEAN,
    responseToReview TEXT,
    responseDate DATE,
    responseAuthor VARCHAR(255),
    responseAuthorRating DECIMAL(3,2),
    responseAuthorLocation VARCHAR(255),
    responseAuthorWebsite VARCHAR(255),
    FOREIGN KEY (productID) REFERENCES Product(id),
    FOREIGN KEY (userID) REFERENCES User(id)
);

CREATE TABLE ProductOffers (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    productID INT UNSIGNED NOT NULL,
    offerType VARCHAR(255),
    offerDetails TEXT,
    offerStartDate DATE,
    offerEndDate DATE,
    discountPercentage DECIMAL(5,2),
    promoCode VARCHAR(255),
    minPurchaseQty INT,
    offerStatus VARCHAR(255),
    offerLimit INT,
    offerUsageCount INT,
    offerDescription TEXT,
    offerTerms VARCHAR(255),
    offerConditions TEXT,
    offerExclusions TEXT,
    offerHighlights TEXT,
    offerAdditionalInfo TEXT,
    offerLocation VARCHAR(255),
    offerAvailability VARCHAR(255),
    offerShippingInfo TEXT,
    offerSeller VARCHAR(255),
    offerSellerRating DECIMAL(3,2),
    offerSellerLocation VARCHAR(255),
    offerSellerContact VARCHAR(255),
    offerSellerWebsite VARCHAR(255),
    maxDiscountAmount DECIMAL(10,2),
    minPurchaseAmount DECIMAL(10,2),
    offerCategory VARCHAR(255),
    offerSubcategory VARCHAR(255),
    offerPrice DECIMAL(10,2),
    offerCreatedBy INT UNSIGNED,
    offerCreatedDate DATETIME,
    offerModifiedBy INT UNSIGNED,
    offerModifiedDate DATETIME,
    FOREIGN KEY (productID) REFERENCES Product(id)
);