CREATE  TABLE hms_dev.t_person ( 
	id_person_key        BIGINT    NOT NULL   PRIMARY KEY,
	id_person_ver        BIGINT       ,
	additional_name      VARCHAR(64)       ,
	address              VARCHAR(255)       ,
	affiliation          BIGINT       ,
	agent_interaction_statistic VARCHAR(255)       ,
	alumni_of            BIGINT       ,
	award                VARCHAR(128)       ,
	birth_date           DATE       ,
	birth_place          VARCHAR(255)       ,
	brand                VARCHAR(128)       ,
	call_sign            VARCHAR(5)       ,
	children             BIGINT       ,
	colleague            BIGINT       ,
	contact_point        BIGINT       ,
	death_date           DATE       ,
	death_place          VARCHAR(255)       ,
	duns                 VARCHAR(255)       ,
	email                VARCHAR(128)       ,
	family_name          VARCHAR(64)       ,
	fax_number           VARCHAR(255)       ,
	follows              BIGINT       ,
	funder               BIGINT       ,
	funding              VARCHAR(255)       ,
	gender               ENUM('MALE','FEMALE','TRANSGENDER','OTHERS')  DEFAULT 'OTHERS'  NOT NULL   ,
	given_name           VARCHAR(128)       ,
	global_location_number VARCHAR(64)       ,
	has_credential       VARCHAR(255)       ,
	has_occupation       VARCHAR(255)       ,
	has_offer_catalog    VARCHAR(255)       ,
	has_pos              VARCHAR(255)       ,
	height               DECIMAL(5,3)       ,
	home_location        VARCHAR(255)       ,
	honorific_prefix     VARCHAR(8)       ,
	honorific_suffix     VARCHAR(8)       ,
	interaction_statistic VARCHAR(255)       ,
	isic_v4              VARCHAR(255)       ,
	job_title            BIGINT       ,
	knows                BIGINT       ,
	knows_about          VARCHAR(255)       ,
	knows_language       BIGINT       ,
	makes_offer          VARCHAR(255)       ,
	member_of            BIGINT       ,
	naics                VARCHAR(255)       ,
	nationality          BIGINT       ,
	net_worth            VARCHAR(255)       ,
	owns                 VARCHAR(255)       ,
	parent               BIGINT       ,
	performer_in         VARCHAR(255)       ,
	publishing_principles VARCHAR(255)       ,
	related_to           BIGINT       ,
	seeks                VARCHAR(255)       ,
	sibling              BIGINT       ,
	sponsor              BIGINT       ,
	spouse               BIGINT       ,
	taxid                VARCHAR(64)       ,
	telephone            VARCHAR(64)       ,
	vat_id               VARCHAR(64)       ,
	weight               DECIMAL(6,3)       ,
	work_location        VARCHAR(255)       ,
	works_for            BIGINT       ,
	additional_type      VARCHAR(255)       ,
	alternate_name       VARCHAR(255)       ,
	description          TEXT       ,
	disambiguating_description TEXT       ,
	identifier           VARCHAR(255)       ,
	image                VARCHAR(255)       ,
	main_entity_of_page  VARCHAR(255)       ,
	name                 VARCHAR(255)       ,
	potential_action     VARCHAR(255)       ,
	same_as              VARCHAR(255)       ,
	subject_of           VARCHAR(255)       ,
	url                  VARCHAR(255)       
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

 
CREATE TABLE Person (
    id_person_key BIGINT NOT NULL PRIMARY KEY,
    id_person_ver BIGINT,
    additional_name VARCHAR(64),
    birth_date DATE,
    birth_place VARCHAR(255),
    call_sign VARCHAR(5),
    death_date DATE,
    death_place VARCHAR(255),
    email VARCHAR(128),
    family_name VARCHAR(64),
    gender ENUM('MALE','FEMALE','TRANSGENDER','OTHERS') DEFAULT 'OTHERS' NOT NULL,
    given_name VARCHAR(128),
    height DECIMAL(5,3)
);

CREATE TABLE Address (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_person_key BIGINT NOT NULL,
    address VARCHAR(255),
    home_location VARCHAR(255),
    FOREIGN KEY (id_person_key) REFERENCES Person(id_person_key)
);

CREATE TABLE Occupation (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_person_key BIGINT NOT NULL,
    has_occupation VARCHAR(255),
    FOREIGN KEY (id_person_key) REFERENCES Person(id_person_key)
);

CREATE TABLE Contact (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_person_key BIGINT NOT NULL,
    fax_number VARCHAR(255),
    contact_point BIGINT,
    FOREIGN KEY (id_person_key) REFERENCES Person(id_person_key)
);