package com.itbd.application.constants.enums;

public enum RoomTypeEnum {
    LIVINGROOM, BEDROOM, KITCHEN, BATHROOM, DININGROOM, STUDYROOM, GUESTROOM, STOREROOM, BALCONY, TERRACE, LAWN, GARDEN,
    GARAGE, PARKING, LOBBY, CORRIDOR, STAIRCASE, LIFT, ELEVATOR, BASEMENT, ATTIC, ROOFTOP, VERANDAH, PORCH, DECK, PATIO,
    POOL, GYM, SPA, SAUNA, JACUZZI, BAR, LOUNGE, CINEMA, THEATRE, CONFERENCE, MEETING, SEMINAR, EXHIBITION, MUSEUM,
    LIBRARY, READING, PRAYER, WORSHIP, TEMPLE, CHURCH, MOSQUE, GURUDWARA, SYNAGOGUE, MONASTERY, CEMETERY, CREMATORIUM,
    GRAVEYARD, BURIAL, CLASSROOM, LABORATORY, WORKSHOP, STUDIO, AUDITORIUM, HALL, CANTEEN, PANTRY, KITCHENETTE,
    RESTAURANT, CAFETERIA, DINING, PUB, CLUB, LECTUREROOM, OFFICE, RECEPTION,
}
